siderolabs/build-container

- .conform.yaml
- .drone.yml
- Dockerfile
Signed-off-by: Andrew Rynhard <andrew@andrewrynhard.com>
> feat: initial implementation

- .drone.yml
Signed-off-by: Andrew Rynhard <andrew@andrewrynhard.com>
> fix: use the correct repo name

- .drone.yml
- Dockerfile
> feat: Upgrading buildkit to v0.4

- Dockerfile
> feat: Upgrade buildkit v0.5

- .drone.yml
- Dockerfile
This allows us to use the Kubernetes driver.
> feat: build buildx from master

- Dockerfile
> feat: add iptables and ip6tables

- Dockerfile
This adds a tool for generating changelogs.
> feat: add git-chglog

- Dockerfile
> fix: move git-chglog install to final stage

- Dockerfile
> test: install UEFI images for QEMU, QEMU for aarch64

- Dockerfile
Allows us to not download it on each build.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
> feat: add codecov bash uploader

- .drone.yml
- Dockerfile
Bump dependencies to the latest available versions.
> chore: bump buildx, docker, alpine, gcloud

- hack/scripts/setup-ci
Need a way to test this better.
> fix: fix the duplicate setup buildkit step

- Dockerfile
Bump gcloud cli to [401.0.0](#57)
> chore: bump gcloud to 401.0.0

- .drone.yml
- Dockerfile
Bump docker to [20.10.18-dind](#60)
> chore: bump docker to 20.10.18-dind

- Dockerfile
Bump docker dind to v20.10.21
Bump Gcloud to 408.0.0
> chore: bump deps

- Dockerfile
* Alpine: 3.16.3
* Google SDK: 410.0.0
> chore: update dependencies

- hack/scripts/setup-ci
See https://github.com/moby/buildkit/releases/tag/v0.11.0
> feat: use buildkit 0.11

- Dockerfile
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
Buildx: v0.10.2
buildkit: v0.11.2
Alpine: 3.7.1
Docker: 20.10.23
Google SDK: 416.0.0
> feat: bump dependencies

- Dockerfile
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
> feat: buildkit v0.11.5

- .github/renovate.json
- Dockerfile
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
> feat: add diffoscope

- Dockerfile
Add `swtpm` and `ovmfctl` for CI QEMU with SecureBoot. Also bump deps.
> feat: add swtpm+ovmfctl

- Dockerfile
Required to push custom images.
> feat: add crane

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
- hack/scripts/setup-ci
> chore: add gh cli

- .drone.yml
- Dockerfile
- hack/scripts/setup-buildx-amd64-arm64
> fix: buildx version

- .drone.yml
Revert build image to default.
> chore: revert build image

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
Add `crane` to build container.
> chore: add crane to build container

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
> feat: add yq executable to both builders

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
> fix: update buildkit

- Dockerfile
> fix: install older OVMF for real

- Dockerfile
> chore: add tf to build container

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
> feat: add sops

- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
This should only affect Drone.
> fix: remove arm64 buildkit builders

- .drone.yml
- Dockerfile.actions-runner-ubuntu-22.04
Add aws cli to the runner image.
> chore: add aws cli

- Dockerfile
> fix: revert base runner image

- Dockerfile
See https://github.com/siderolabs/talos/pull/9555
> fix: add mkisofs to the build env

- Dockerfile
Test new actions runner image.
> chore: test actions runner upgrade

- .github/renovate.json
- .github/workflows/slack-notify.yaml
- .kres.yaml
- Dockerfile
- Makefile
- hack/scripts/setup-ci
Build actions runner image using source Dockerfile with our own modifications.
This adds the extra required packages and updates Ubuntu version to a more reasonale modern one.
> feat: build runner image from source
