- .drone.yml
- Dockerfile
- Adds docker buildx command 
- Upgrade docker to 19.03 rc to support buildx
- Clean up initial base layer ( remove go )
- Download gitmeta binary instead of compile on the fly
> feat: Add docker buildx

- Dockerfile
- Update docker/buildx 0.2.2 -> 0.3.0
- Update docker/compose 1.24.0 -> 1.24.1
- Update docker/docker 19.03-rc -> 19.03.1
- Update moby/buildkit 0.5.0 -> 0.6.1
- Update gitmeta alpha.0 -> alpha.2
> chore: Update component versions

- Dockerfile
Bundle azure, gcp, aws cli in build container so we can make use
of these cli during build time without needing to redownload them.
> feat: Add cloud provider CLIs

- Dockerfile
Release: https://github.com/talos-systems/gitmeta/releases/tag/v0.1.0-alpha.3
> chore: bump gitmeta to 0.1.0-alpha3

- Dockerfile
Builds are going via dockerfile frontend, so `bldr` CLI is not used,
only docker image.
> chore: remove `bldr` from build-container

- .drone.yml
- Dockerfile
This prepares for `osctl cluster` via Firecracker for Talos build.
> chore: add firecracker & CNI plugins

- Dockerfile
This fixes `bridge` when kernel doesn't have
`CONFIG_BRIDGE_VLAN_FILTERING`.
See https://github.com/containernetworking/plugins/releases/tag/v0.8.5
> chore: update cni plugins to v0.8.5

- .drone.yml
This pulls in a fix for
https://github.com/firecracker-microvm/firecracker/issues/1560.
> chore: update firecracker to the last commit from master

- Dockerfile
Linux `bzImage` is using some version of `xz` compression which no
native golang `xz` library can decompress.
> chore: add `xz` for upcoming Firecracker "bootloader"

- .drone.yml
- Dockerfile
Release notes: https://github.com/firecracker-microvm/firecracker/releases/tag/v0.21.0
> chore: use Firecracker 0.21 release

- Dockerfile
- hack/scripts/install-ci-key
- hack/scripts/setup-buildx-amd64-arm64
This will be used temporarily at least for bldr and bldr-based projects
to bootstrap arm64 toolchain and packages.
> chore: add helper scripts to set up amd64/arm64 builders

- hack/scripts/setup-buildx-amd64-arm64
It was specific to bldr and related to registry.ci.svc,
we don't neet it for now.
> chore: remove hack/buildkit.conf

- .drone.yml
- Dockerfile
Switch to ARG to keep the environment clean.
Install `buildx` from the official release.
Bump versions.
> chore: update versions of components

- .drone.yml
- Dockerfile
QEMU executable is required to run e2e functional tests.
Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
> test: add qemu and libvirt packages into container

- Dockerfile
This PR gets rid of python 2.x for our build container. It was needed
for the old azure-cli release and the gcloud sdk. Both components now
support python 3.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
> chore: update build container to remove python2

- Dockerfile
- hack/buildkit.conf
This config can be used to whitelist registry.ci.svc as insecure
registry.
> chore: add buildkit.conf as a file

- hack/buildkit.conf
- hack/scripts/setup-buildx-amd64-arm64
`xbuild` is used by default in toolchain, tools, pkgs
> fix: update builkit.conf, move default xbuild builder to new docker

- Dockerfile
19.03.13 is the latest version, this should hopefully pull newer buildx
version.
> chore: upgrade Docker to the latest release

- Dockerfile
We need real tar, not busybox version.
> chore: add tar

- Dockerfile
- hack/scripts/setup-ci
A helper script for setting up buildkit and git tags.
> feat: add setup-ci script

- hack/scripts/setup-ci
The `docker` CLI wasn't very happy about using an environment variable for the args. It was
interpreting the whole string as a single arg.
> fix: don't use env var for common args

- hack/scripts/setup-ci
> fix: skip tag creation if tag exists

- Dockerfile
- hack/buildkit.conf
`pkgs` repo has LFS enabled, and `git-lfs` is required for correct
status.
> chore: add git-lfs to build-container

- hack/scripts/setup-ci
This fixes `sed` expression so that `$TAG` is empty if current commit
doesn't have format of `release(v0.x.y)`.
> fix: extraction of tag from release PR

- Dockerfile
> fix: release build depends on `sed` features not available in busybox

- hack/scripts/setup-ci
> chore: use buildx-stable for buildkit

- Dockerfile
- hack/scripts/setup-ci
This workarounds an issue with entitlements.
Also provide a way to boot amd64-only buildkit worker (to be used later
in Talos to speed up builds).
> chore: use forked buildkit image

- .drone.yml
- Dockerfile
Disable ci for renovate/dependabot updates.
> chore: don't run ci on renovate/dependabot updates

- Dockerfile
It looks like Alpine package is broken atm.
> fix: install s3cmd via pip

- Dockerfile
> chore: bump gcloud cli

- hack/scripts/buildkit.toml
- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
Looks like buildkit is doing too aggressive GC, which leads to crazy slow builds.
> feat: add explicit buildkit GC configuration

- Dockerfile
`ovmfctl` is no longer needed after https://github.com/siderolabs/talos/pull/7403
Also bump deps.
> chore: remove ovmfctl

- hack/scripts/setup-buildx-amd64-arm64
- hack/scripts/setup-ci
The buildkit 0.12 drops the `moby.buildkit.buildinfo.v1` annotation which breaks the image reproducibility for some container images.
> feat: update buildkit to 0.12.2

- Dockerfile
We suspect it might be causing issues with SecureBoot.
> fix: rollback alpine to 3.18

- Dockerfile
Trying with older OVMF from 3.18.
> fix: bring back Alpine to 3.19, but revert OVMF

- Dockerfile
- Dockerfile.actions-runner-ubuntu-22.04
Talos requires it now for e2e tests.
> feat: add zstd tool

- hack/scripts/setup-ci
From https://github.com/siderolabs/kres/pull/428
> chore: bump moby/buildkit to v0.15.1

- .github/renovate.json
- Dockerfile
- hack/scripts/setup-ci
Drop Azure and Gcloud cli, CI doesn't use them anymore.
Migrate renovate config to new schema.
> chore: bump deps
